account_filters:
  mysql:
    exclude_patterns:
      - "mysql%"

  postgresql:
    exclude_users:
      - rdsadmin
      - rds_superuser
    exclude_patterns:
      - pg_%

  sqlserver:
    exclude_users:
      - public
      - guest
      - dbo
    exclude_patterns:
      - "##%"
      - "NT SERVICE\\%"
      - "NT AUTHORITY\\%"
      - "BUILTIN\\%"
      - "NT %"

  oracle:
    exclude_users:
      - SCOTT
      - CTXSYS
      - EXFSYS
      - MDDATA
      - APPQOSSYS
      - OUTLN
      - DIP
      - TSMSYS
      - WMSYS
      - XDB
      - ANONYMOUS
      - ORDPLUGINS
      - ORDSYS
      - SI_INFORMTN_SCHEMA
      - MDSYS
      - OLAPSYS
      - SPATIAL_CSW_ADMIN_USR
      - SPATIAL_WFS_ADMIN_USR
      - APEX_PUBLIC_USER
      - APEX_030200
      - FLOWS_FILES
      - HR
      - OE
      - PM
      - IX
      - SH
      - BI
      - DEMO
      - ADMIN
      - AUDSYS
      - GSMADMIN_INTERNAL
      - GSMCATUSER
      - GSMUSER
      - LBACSYS
      - OJVMSYS
      - ORACLE_OCM
      - ORDDATA
      - ORDS_METADATA
      - ORDS_PUBLIC_USER
      - PDBADMIN
      - RDSADMIN
      - REMOTE_SCHEDULER_AGENT
      - SYSBACKUP
      - SYSDG
      - SYSKM
      - SYSRAC
      - SYS$UMF
      - XS$NULL
      - OWBSYS
      - OWBSYS_AUDIT
    exclude_patterns:
      - SYS$%
      - GSM%
      - XDB%
      - APEX%
      - ORD%
      - SPATIAL_%
