database_filters:
  mysql:
    exclude_databases:
      - information_schema
      - performance_schema
      - mysql
      - sys
    exclude_patterns:
      - "tmp_%"
      - "temp_%"
      - "#sql%"

  postgresql:
    exclude_databases:
      - template0
      - template1
      - postgres
    exclude_patterns:
      - "pg_%"

  sqlserver:
    exclude_databases:
      - master
      - model
      - msdb
      - tempdb
    exclude_patterns:
      - "ReportServer%"

  oracle:
    exclude_databases:
      - SYSTEM
      - SYSAUX
      - USERS
    exclude_patterns:
      - "SYS%"
      - "SYSTEM%"
